import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { ConfigProvider } from 'antd';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#7F3DFF',
            colorError: '#FE4D4F',
          },
        }}
      >
        <body className={montserrat.className}> {children}</body>
      </ConfigProvider>
    </html>
  );
}
